package cl.subtel.model.common.web;
// Generated 03-07-2017 14:39:15 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MineducEstados generated by hbm2java
 */
public class MineducEstados implements java.io.Serializable {

	private int mineducEstadoId;
	private String mineducEstadoTx;
	private Integer padreId;
	private Set rbdEstadoses = new HashSet(0);

	public MineducEstados() {
	}

	public MineducEstados(int mineducEstadoId) {
		this.mineducEstadoId = mineducEstadoId;
	}

	public MineducEstados(int mineducEstadoId, String mineducEstadoTx, Integer padreId, Set rbdEstadoses) {
		this.mineducEstadoId = mineducEstadoId;
		this.mineducEstadoTx = mineducEstadoTx;
		this.padreId = padreId;
		this.rbdEstadoses = rbdEstadoses;
	}

	public int getMineducEstadoId() {
		return this.mineducEstadoId;
	}

	public void setMineducEstadoId(int mineducEstadoId) {
		this.mineducEstadoId = mineducEstadoId;
	}

	public String getMineducEstadoTx() {
		return this.mineducEstadoTx;
	}

	public void setMineducEstadoTx(String mineducEstadoTx) {
		this.mineducEstadoTx = mineducEstadoTx;
	}

	public Integer getPadreId() {
		return this.padreId;
	}

	public void setPadreId(Integer padreId) {
		this.padreId = padreId;
	}

	public Set getRbdEstadoses() {
		return this.rbdEstadoses;
	}

	public void setRbdEstadoses(Set rbdEstadoses) {
		this.rbdEstadoses = rbdEstadoses;
	}

}
