package cl.subtel.model.common.web;
// Generated 03-07-2017 14:39:15 by Hibernate Tools 5.2.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Operadoras generated by hbm2java
 */
public class Operadoras implements java.io.Serializable {

	private int operadoraId;
	private String nombreSocialTx;
	private String aliasTx;
	private String observacionTx;
	private BigDecimal rut;
	private String usuarioSftp;

	public Operadoras() {
	}

	public Operadoras(int operadoraId) {
		this.operadoraId = operadoraId;
	}

	public Operadoras(int operadoraId, String nombreSocialTx, String aliasTx, String observacionTx, BigDecimal rut,
			String usuarioSftp) {
		super();
		this.operadoraId = operadoraId;
		this.nombreSocialTx = nombreSocialTx;
		this.aliasTx = aliasTx;
		this.observacionTx = observacionTx;
		this.rut = rut;
		this.usuarioSftp = usuarioSftp;
	}

	public int getOperadoraId() {
		return operadoraId;
	}

	public void setOperadoraId(int operadoraId) {
		this.operadoraId = operadoraId;
	}

	public String getNombreSocialTx() {
		return nombreSocialTx;
	}

	public void setNombreSocialTx(String nombreSocialTx) {
		this.nombreSocialTx = nombreSocialTx;
	}

	public String getAliasTx() {
		return aliasTx;
	}

	public void setAliasTx(String aliasTx) {
		this.aliasTx = aliasTx;
	}

	public String getObservacionTx() {
		return observacionTx;
	}

	public void setObservacionTx(String observacionTx) {
		this.observacionTx = observacionTx;
	}

	public BigDecimal getRut() {
		return rut;
	}

	public void setRut(BigDecimal rut) {
		this.rut = rut;
	}

	public String getUsuarioSftp() {
		return usuarioSftp;
	}

	public void setUsuarioSftp(String usuarioSftp) {
		this.usuarioSftp = usuarioSftp;
	}
}
