package cl.subtel.model.common.web;
// Generated 03-07-2017 14:39:15 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * RbdEstados generated by hbm2java
 */
public class RbdEstados implements java.io.Serializable {

	private int rbdEstadoId;
	private AdjudicadoEstados adjudicadoEstados;
	private ConectadoEstados conectadoEstados;
	private MineducEstados mineducEstados;
	private Integer rbdConcursoId;
	private Date fechaI;
	private Date fechaF;

	public RbdEstados() {
	}

	public RbdEstados(int rbdEstadoId, Date fechaI) {
		this.rbdEstadoId = rbdEstadoId;
		this.fechaI = fechaI;
	}

	public RbdEstados(int rbdEstadoId, AdjudicadoEstados adjudicadoEstados, ConectadoEstados conectadoEstados,
			MineducEstados mineducEstados, Integer rbdConcursoId, Date fechaI, Date fechaF) {
		this.rbdEstadoId = rbdEstadoId;
		this.adjudicadoEstados = adjudicadoEstados;
		this.conectadoEstados = conectadoEstados;
		this.mineducEstados = mineducEstados;
		this.rbdConcursoId = rbdConcursoId;
		this.fechaI = fechaI;
		this.fechaF = fechaF;
	}

	public int getRbdEstadoId() {
		return this.rbdEstadoId;
	}

	public void setRbdEstadoId(int rbdEstadoId) {
		this.rbdEstadoId = rbdEstadoId;
	}

	public AdjudicadoEstados getAdjudicadoEstados() {
		return this.adjudicadoEstados;
	}

	public void setAdjudicadoEstados(AdjudicadoEstados adjudicadoEstados) {
		this.adjudicadoEstados = adjudicadoEstados;
	}

	public ConectadoEstados getConectadoEstados() {
		return this.conectadoEstados;
	}

	public void setConectadoEstados(ConectadoEstados conectadoEstados) {
		this.conectadoEstados = conectadoEstados;
	}

	public MineducEstados getMineducEstados() {
		return this.mineducEstados;
	}

	public void setMineducEstados(MineducEstados mineducEstados) {
		this.mineducEstados = mineducEstados;
	}

	public Integer getRbdConcursoId() {
		return this.rbdConcursoId;
	}

	public void setRbdConcursoId(Integer rbdConcursoId) {
		this.rbdConcursoId = rbdConcursoId;
	}

	public Date getFechaI() {
		return this.fechaI;
	}

	public void setFechaI(Date fechaI) {
		this.fechaI = fechaI;
	}

	public Date getFechaF() {
		return this.fechaF;
	}

	public void setFechaF(Date fechaF) {
		this.fechaF = fechaF;
	}

}
