package cl.subtel.model.common.web;
// Generated 03-07-2017 14:39:15 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Regiones generated by hbm2java
 */
public class Regiones implements java.io.Serializable {

	private int regionId;
	private String nombreRegionTx;
	private String numeroRegionTx;
	private Set comunases = new HashSet(0);
	private Set comunases_1 = new HashSet(0);

	public Regiones() {
	}

	public Regiones(int regionId) {
		this.regionId = regionId;
	}

	public Regiones(int regionId, String nombreRegionTx, String numeroRegionTx, Set comunases, Set comunases_1) {
		this.regionId = regionId;
		this.nombreRegionTx = nombreRegionTx;
		this.numeroRegionTx = numeroRegionTx;
		this.comunases = comunases;
		this.comunases_1 = comunases_1;
	}

	public int getRegionId() {
		return this.regionId;
	}

	public void setRegionId(int regionId) {
		this.regionId = regionId;
	}

	public String getNombreRegionTx() {
		return this.nombreRegionTx;
	}

	public void setNombreRegionTx(String nombreRegionTx) {
		this.nombreRegionTx = nombreRegionTx;
	}

	public String getNumeroRegionTx() {
		return this.numeroRegionTx;
	}

	public void setNumeroRegionTx(String numeroRegionTx) {
		this.numeroRegionTx = numeroRegionTx;
	}

	public Set getComunases() {
		return this.comunases;
	}

	public void setComunases(Set comunases) {
		this.comunases = comunases;
	}

	public Set getComunases_1() {
		return this.comunases_1;
	}

	public void setComunases_1(Set comunases_1) {
		this.comunases_1 = comunases_1;
	}

}
