package cl.subtel.model.common.web;
// Generated 03-07-2017 14:39:15 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoAdjudicaciones generated by hbm2java
 */
public class TipoAdjudicaciones implements java.io.Serializable {

	private int tipoAdjId;
	private String tipoEsperaTx;
	private String descripcionTx;
	private Set adjudicacioneses = new HashSet(0);
	private Set instalacioneses = new HashSet(0);
	private Set listaEsperas = new HashSet(0);

	public TipoAdjudicaciones() {
	}

	public TipoAdjudicaciones(int tipoAdjId) {
		this.tipoAdjId = tipoAdjId;
	}

	public TipoAdjudicaciones(int tipoAdjId, String tipoEsperaTx, String descripcionTx, Set adjudicacioneses,
			Set instalacioneses, Set listaEsperas) {
		this.tipoAdjId = tipoAdjId;
		this.tipoEsperaTx = tipoEsperaTx;
		this.descripcionTx = descripcionTx;
		this.adjudicacioneses = adjudicacioneses;
		this.instalacioneses = instalacioneses;
		this.listaEsperas = listaEsperas;
	}

	public int getTipoAdjId() {
		return this.tipoAdjId;
	}

	public void setTipoAdjId(int tipoAdjId) {
		this.tipoAdjId = tipoAdjId;
	}

	public String getTipoEsperaTx() {
		return this.tipoEsperaTx;
	}

	public void setTipoEsperaTx(String tipoEsperaTx) {
		this.tipoEsperaTx = tipoEsperaTx;
	}

	public String getDescripcionTx() {
		return this.descripcionTx;
	}

	public void setDescripcionTx(String descripcionTx) {
		this.descripcionTx = descripcionTx;
	}

	public Set getAdjudicacioneses() {
		return this.adjudicacioneses;
	}

	public void setAdjudicacioneses(Set adjudicacioneses) {
		this.adjudicacioneses = adjudicacioneses;
	}

	public Set getInstalacioneses() {
		return this.instalacioneses;
	}

	public void setInstalacioneses(Set instalacioneses) {
		this.instalacioneses = instalacioneses;
	}

	public Set getListaEsperas() {
		return this.listaEsperas;
	}

	public void setListaEsperas(Set listaEsperas) {
		this.listaEsperas = listaEsperas;
	}

}
