package cl.subtel.model.common.sla;
// Generated 03-07-2017 14:37:34 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Feriados generated by hbm2java
 */
public class Feriados implements java.io.Serializable {

	private int feriadoId;
	private Date fecha;
	private String motivo;

	public Feriados() {
	}

	public Feriados(int feriadoId) {
		this.feriadoId = feriadoId;
	}

	public Feriados(int feriadoId, Date fecha, String motivo) {
		this.feriadoId = feriadoId;
		this.fecha = fecha;
		this.motivo = motivo;
	}

	public int getFeriadoId() {
		return this.feriadoId;
	}

	public void setFeriadoId(int feriadoId) {
		this.feriadoId = feriadoId;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

}
