package cl.subtel.model.common.sla;
// Generated 03-07-2017 14:37:34 by Hibernate Tools 5.2.0.CR1

/**
 * Prefacturas2 generated by hbm2java
 */
public class Prefacturas2 implements java.io.Serializable {

	private int prefacturaid;
	private Archivos archivos;

	public Prefacturas2() {
	}

	public Prefacturas2(int prefacturaid) {
		this.prefacturaid = prefacturaid;
	}

	public Prefacturas2(int prefacturaid, Archivos archivos) {
		this.prefacturaid = prefacturaid;
		this.archivos = archivos;
	}

	public int getPrefacturaid() {
		return this.prefacturaid;
	}

	public void setPrefacturaid(int prefacturaid) {
		this.prefacturaid = prefacturaid;
	}

	public Archivos getArchivos() {
		return this.archivos;
	}

	public void setArchivos(Archivos archivos) {
		this.archivos = archivos;
	}

}
