package cl.subtel.model.common.sla;
// Generated 03-07-2017 14:37:34 by Hibernate Tools 5.2.0.CR1

import java.math.BigDecimal;

/**
 * PromedioMensualDispo generated by hbm2java
 */
public class PromedioMensualDispo implements java.io.Serializable {

	private int promedioId;
	private Archivos archivos;
	private BigDecimal promedioDisponibilidadNu;
	private Integer rbdNu;

	public PromedioMensualDispo() {
	}

	public PromedioMensualDispo(int promedioId) {
		this.promedioId = promedioId;
	}

	public PromedioMensualDispo(Archivos archivos, BigDecimal promedioDisponibilidadNu, Integer rbdNu) {
		this.archivos = archivos;
		this.promedioDisponibilidadNu = promedioDisponibilidadNu;
		this.rbdNu = rbdNu;
	}

	public int getPromedioId() {
		return this.promedioId;
	}

	public void setPromedioId(int promedioId) {
		this.promedioId = promedioId;
	}

	public Archivos getArchivos() {
		return this.archivos;
	}

	public void setArchivos(Archivos archivos) {
		this.archivos = archivos;
	}

	public BigDecimal getPromedioDisponibilidadNu() {
		return this.promedioDisponibilidadNu;
	}

	public void setPromedioDisponibilidadNu(BigDecimal promedioDisponibilidadNu) {
		this.promedioDisponibilidadNu = promedioDisponibilidadNu;
	}

	public Integer getRbdNu() {
		return this.rbdNu;
	}

	public void setRbdNu(Integer rbdNu) {
		this.rbdNu = rbdNu;
	}

}
