package cl.subtel.model.common.sla;
// Generated 03-07-2017 14:37:34 by Hibernate Tools 5.2.0.CR1

import java.math.BigDecimal;

/**
 * PromedioMensualVel generated by hbm2java
 */
public class PromedioMensualVel implements java.io.Serializable {

	private int promedioId;
	private Archivos archivos;
	private BigDecimal promedioVelSubidaNu;
	private BigDecimal promedioVelBajadaNu;
	private Integer rbdNu;

	public PromedioMensualVel() {
	}

	public PromedioMensualVel(int promedioId) {
		this.promedioId = promedioId;
	}

	public PromedioMensualVel(Archivos archivos, BigDecimal promedioVelSubidaNu,
			BigDecimal promedioVelBajadaNu, Integer rbdNu) {
		this.archivos = archivos;
		this.promedioVelSubidaNu = promedioVelSubidaNu;
		this.promedioVelBajadaNu = promedioVelBajadaNu;
		this.rbdNu = rbdNu;
	}

	public int getPromedioId() {
		return this.promedioId;
	}

	public void setPromedioId(int promedioId) {
		this.promedioId = promedioId;
	}

	public Archivos getArchivos() {
		return this.archivos;
	}

	public void setArchivos(Archivos archivos) {
		this.archivos = archivos;
	}

	public BigDecimal getPromedioVelSubidaNu() {
		return this.promedioVelSubidaNu;
	}

	public void setPromedioVelSubidaNu(BigDecimal promedioVelSubidaNu) {
		this.promedioVelSubidaNu = promedioVelSubidaNu;
	}

	public BigDecimal getPromedioVelBajadaNu() {
		return this.promedioVelBajadaNu;
	}

	public void setPromedioVelBajadaNu(BigDecimal promedioVelBajadaNu) {
		this.promedioVelBajadaNu = promedioVelBajadaNu;
	}

	public Integer getRbdNu() {
		return this.rbdNu;
	}

	public void setRbdNu(Integer rbdNu) {
		this.rbdNu = rbdNu;
	}

}
